#!/usr/bin/python
import numpy as np
class Particula:
    #atributos
    cargada= True
    #instancias

def __init__(self,x,y,z,vx,vy,vz,m,carga):
    self.X=x
        self.Y=y
        self.Z=z
        self.VX=vx
        self.VY=vy
        self.VZ=vz
        self.M=m
        self.Carga=carga
    def Pos_evol(self,w,t):
        self.X=np.sen(wt))
        self.Y=np.cos(wt)-1
        self.Z=np.VZ*t
Par1=Particula(1.0,1.0,1.0,1.0,1.0,1.0,1.0,1)
print(Par1.X,Par1.Y,Par1.Z,Par1.VX,Par1.VY,Par1.VZ,Par1.M,Par1.Carga)

for i in range(1,10):
    Par1.Pos_evol(1.0,0.0,0.0,0.1)
    print(Par1.X,Par1.Y,Par1.Z,Par1.VX,Par1.VY,Par1.VZ,Par1.M,Par1.Carga)
    

  
 
